# Generated by Django 3.1.6 on 2021-02-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProdcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fieldsType', models.TextField()),
                ('fieldsName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('ageLimit', models.IntegerField()),
                ('pathPoster', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('TypeProdcut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typeprodcut')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('condition', models.CharField(max_length=150)),
                ('location', models.TextField()),
                ('sumary', models.TextField()),
                ('production_year', models.DateField()),
                ('pathPoster', models.TextField()),
                ('amountRoon', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('typeProdcut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typeprodcut')),
            ],
        ),
    ]
