# Generated by Django 3.1.6 on 2021-02-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeProdcut',
            new_name='TypeProduct',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='typeProdcut',
            new_name='typeProduct',
        ),
        migrations.RenameField(
            model_name='novel',
            old_name='TypeProdcut',
            new_name='typeProduct',
        ),
    ]
