# Generated by Django 3.1.6 on 2021-02-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210218_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='sumary',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='house',
            name='production_year',
        ),
    ]
